model:
  # base_learning_rate: 1.0e-5
  base_learning_rate: 5.0e-6
  target: ldm.models.autoencoder.BaseAutoencoder
  params:
    monitor: "val/rec_loss"
    # ckpt_path: models/pretrained/ldm_gen_ffhq_256_first_stage_model.ckpt
    ckpt_path: logs/2023-10-29T15-13-24_encoder_for_gen_ffhq_64_64x64x3_256/checkpoints/epoch=000007.ckpt
    # ignore_keys: ['decoder', 'post_quant_conv']
    freeze_encoder: True
    lossconfig:
      target: ldm.modules.losses.EncoderLoss
      params: {}

    ddconfig:
      double_z: False
      z_channels: 3
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,2,4 ]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0

    liifconfig:
      out_dim: 3
      hidden_list: [256, 256, 256, 256]
      cell_decode: True
      local_ensemble: True

    trainconfig:
      image_key: image
      gt_min: 64
      gt_max: 256
      inp_key: hr

    valconfig:
      image_key: image
      gt_min: 256
      gt_max: 256
      inp_key: hr


data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 8
    wrap: True
    train:
      target: ldm.data.datasets.SingleDataset
      params:
        root_path: ../datasets/ffhq
        img_size: 256
        cache: bin
    validation:
      target: ldm.data.datasets.SingleDataset
      params:
        root_path: ../datasets/ffhq
        img_size: 256
        first_k: 100
        cache: bin

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 5000
        max_images: 8
        increase_log_steps: False
        log_first_step: True
        log_all_val: True

  trainer:
    benchmark: True